name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Add
      id: add
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Add
        setup-command: npm install
        command: npm run test:add
        timeout: 1
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        ADD_RESULTS: "${{steps.add.outputs.result}}"
      with:
        runners: add
